### PR TITLE
feat: remove the kubernetes helper function to remove k8s dependecies!

### PR DESCRIPTION
**Pull request by dirien**
Hi Civo,

This PR removes the kubernetes helper method from the `civogo` libary as it introduce a whole lot of k8s dependecies.

The line https://github.com/civo/civogo/blob/206c95882931399cc54016224317fc6401d7d1df/go.mod#L9 here, introduce this:

```
k8s.io/api v0.21.2 // indirect
k8s.io/apimachinery v0.21.2 // indirect
k8s.io/client-go v0.21.2 // indirect
k8s.io/klog/v2 v2.8.0 // indirect
k8s.io/utils v0.0.0-20201110183641-67b214c5f920 // indirect
sigs.k8s.io/structured-merge-diff/v4 v4.1.0 // indirect
sigs.k8s.io/yaml v1.2.0 // indirect
```

Reason: It makes it difficult to include CIVO in other OSS projects because of this libraries.

Tagging @alejandrojnm for further discussions.

### CODE REVIEW

**Comment by dirien** [comment]
The helper function got introduced in #107

**Comment by alejandrojnm** [comment]
@RealHarshThakur you add this feature, I think we don't need it, but in the future, we can do this in the client (CLI).

**Comment by RealHarshThakur** [comment]
@dirien which Go version would you like to use?

**Comment by dirien** [comment]
@RealHarshThakur I don't mind.

**Comment by RealHarshThakur** [comment]
I was thinking we would be okay with adding k8s dependencies since we only maintain latest Go versions(1.17 to 1.19) but I can understand this causing unwanted trouble, so I'm okay with this

**Review by RealHarshThakur — APPROVED** [review]

**Comment by RealHarshThakur** [comment]
@dirien  Pipeline seems to be failing. Have you run go mod tidy?

**Comment by dirien** [comment]
HI @RealHarshThakur, ohh sorry! I fixed it! :)

**Comment by RealHarshThakur** [comment]
Weird, it still fails in pipeline

**Comment by dirien** [comment]
Hi @RealHarshThakur,

now it should run fine! Tried it in a container, to avoid any side-effects form my local machine.

```bash
root@e9e50ff70a47:/workspace#  go test ./...
go: downloading github.com/onsi/gomega v1.19.0
go: downloading golang.org/x/net v0.0.0-20220225172249-27dd8689420f
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading golang.org/x/text v0.3.7
ok      github.com/civo/civogo  0.072s
?       github.com/civo/civogo/utils    [no test files]
root@e9e50ff70a47:/workspace# 
```

**Pull request merged**
