### PR TITLE
Feature/loadbalancer

### PR DESCRIPTION
**Pull request by alejandrojnm**
- Now can add, delete update and list the load balance

### CODE REVIEW

**Comment by andyjeffries** [comment]
Hey, `LoadBalance` should be `LoadBalancer` - aside from that, all good to merge.

**Comment by alejandrojnm** [comment]
OK, i will make all the changes

**Comment by andyjeffries** [comment]
Hopefully final comments on this - you have definitions like `LoadBalancer` and `TestListLoadbalancer` - we should be consistent on capitalisation, so it should always be `LoadBalancer` not `Loadbalancer`. Thanks.

**Comment by alejandrojnm** [comment]
True, sorry for that i coding at 2 AM 😢

**Comment by andyjeffries** [comment]
Thanks @alejandrojnm

**Comment by andyjeffries** [comment]
@alejandrojnm made some minor changes in b8d5ddb to field names and a method name, these may affect your work in the Terraform module.

**Comment by andyjeffries** [comment]
Golint was complaining in my editor (squiggly yellow underlines in VS Code) about `Tls` should be `TLS` and all the other modules are using `Create...` to create a resource rather than `New...`.

**Comment by alejandrojnm** [comment]
It ok for me, I don’t use this module in terraform until now

**Pull request merged**
